#!/usr/bin/env python3
"""
excel_to_diya.py

Reads an optical plate-map Excel file and generates a ready-to-run
Diya Python script with the Red and Green optical power matrices filled in.

Usage:
    python excel_to_diya.py <input.xlsx> [output_script.py]
        [--sheet "Plate map"]
        [--on-time 5]
        [--period 5]
        [--temperature 37.0]
        [--experiment-id YX001]

The script searches the chosen sheet for:
  • A cell containing "Red"   followed by an 8-row × 12-col numeric block
  • A cell containing "Green" followed by an 8-row × 12-col numeric block

Both blocks are expected to have row labels A-H in column 0 and column
labels 1-12 in the header row immediately after the colour label.
"""

import argparse
import sys
import textwrap
from pathlib import Path

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ROWS = list("ABCDEFGH")   # 8 plate rows
NCOLS = 12


def find_block(df: pd.DataFrame, label: str) -> np.ndarray:
    """
    Locate a cell whose string value matches *label* (case-insensitive),
    then extract the 8×12 numeric grid that follows it.

    Expected layout (row-relative to the label cell):
        label_row   : label text in col C
        label_row+1 : header row  (col C = NaN, cols C+1..C+12 = 1..12)
        label_row+2 : row A data  (col C = 'A', cols C+1..C+12 = values)
        ...
        label_row+9 : row H data
    """
    label_lower = label.lower()

    for r in range(len(df)):
        for c in range(len(df.columns)):
            cell = df.iat[r, c]
            if isinstance(cell, str) and cell.strip().lower() == label_lower:
                # Header is at r+1, data rows at r+2 .. r+9
                data_start_row = r + 2
                data_start_col = c + 1          # skip the row-label column

                matrix = []
                for row_idx in range(8):
                    actual_row = data_start_row + row_idx
                    row_data = []
                    for col_idx in range(NCOLS):
                        val = df.iat[actual_row, data_start_col + col_idx]
                        try:
                            row_data.append(float(val))
                        except (TypeError, ValueError):
                            row_data.append(0.0)
                    matrix.append(row_data)

                arr = np.array(matrix)
                if arr.shape != (8, 12):
                    raise ValueError(
                        f"Expected 8×12 block for '{label}', got {arr.shape}"
                    )
                return arr

    raise ValueError(
        f"Could not find a cell labelled '{label}' in the sheet. "
        "Make sure the sheet contains a cell with exactly that text."
    )


def format_matrix(arr: np.ndarray, indent: int = 8) -> str:
    """Render an 8×12 numpy array as a tidy Python literal."""
    pad = " " * indent
    rows_str = []
    for i, row in enumerate(arr):
        values = ",\t".join(f"{round(v, 6)}" for v in row)
        rows_str.append(f"{pad}[{values}],  # Row {ROWS[i]}")
    return "np.array([\n" + "\n".join(rows_str) + "\n" + " " * (indent - 4) + "])"


def generate_script(
    red: np.ndarray,
    green: np.ndarray,
    on_time: float,
    period: float,
    temperature: float,
    experiment_id: str,
    source_file: str,
) -> str:
    red_str   = format_matrix(red,   indent=4)
    green_str = format_matrix(green, indent=4)

    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        # -*- coding: utf-8 -*-
        # Auto-generated by excel_to_diya.py
        # Source: {source_file}

        import numpy as np
        import argparse
        import sys
        from diya import (diya, load_power_matrix_from_csv, prepare_protocol,
                          load_device_config, generate_color_help_text, NROWS, NCOLS,
                          get_reference_powers, load_device_calibration,
                          upload_protocol)

        ##############################################################################
        ########################### USER CONFIGURATION ###############################
        ##############################################################################

        # Optical power matrix, in mW/cm2
        # 3D array: [channel, row, column]
        # Channel 1 = Green light (Color 1, LEDG1)
        # Channel 3 = Red   light (Color 3, LEDG1)
        DEFAULT_OPTICAL_POWER = np.array([
            # Channel 0 – Blue (unused, all zeros)
            np.zeros((NROWS, NCOLS)),

            # Channel 1 – Green light
            {green_str},

            # Channel 2 – Yellow-Green / White (unused, all zeros)
            np.zeros((NROWS, NCOLS)),

            # Channel 3 – Red light
            {red_str},
        ])

        # Timing parameters (in seconds)
        DEFAULT_ON_TIME   = {on_time}   # On time
        DEFAULT_PERIOD    = {period}    # Period (on + off)

        # Temperature setpoint (°C)
        DEFAULT_TEMPERATURE = {temperature}

        ##############################################################################
        ############################ ADVANCED OPTIONS ################################
        ##############################################################################

        DEFAULT_START_TIME    = np.zeros((NROWS, NCOLS))
        DEFAULT_ON_TIME_MATRIX = None
        DEFAULT_GROUP  = 1   # LEDG1 (colors 0-3)
        DEFAULT_COLOR  = 0

        ##############################################################################
        ######################## END USER CONFIGURATION ##############################
        ##############################################################################

        parser = argparse.ArgumentParser(
            description='Upload {experiment_id} protocol to DIYA device'
        )
        parser.add_argument('device_id', type=str, help='Device ID (e.g., diya00)')

        parser.add_argument('--power-matrix-csv',     type=str)
        parser.add_argument('--start-time-csv',       type=str)
        parser.add_argument('--on-time-csv',          type=str)
        parser.add_argument('--color',                type=int, default=DEFAULT_COLOR,
                            help=generate_color_help_text())
        parser.add_argument('--led-group',            type=int, default=DEFAULT_GROUP,
                            choices=[1, 2])
        parser.add_argument('--on-time',              type=float, default=DEFAULT_ON_TIME)
        parser.add_argument('--period',               type=float, default=DEFAULT_PERIOD)
        parser.add_argument('--lpwm-value',           type=int)
        parser.add_argument('--temperature',          type=float, default=DEFAULT_TEMPERATURE)
        parser.add_argument('--no-verify',            action='store_true')
        parser.add_argument('--debug',                action='store_true')
        parser.add_argument('--no-progress',          action='store_true')
        parser.add_argument('--no-reset',             action='store_true')
        parser.add_argument('--dry-run',              action='store_true')
        parser.add_argument('--no-calibration',       action='store_true')
        parser.add_argument('--disable-current-scaling', action='store_true')
        parser.add_argument('--verbose',              action='store_true')
        args = parser.parse_args()

        device_id     = args.device_id
        selected_group = args.led_group

        power_matrix = DEFAULT_OPTICAL_POWER.copy()

        if args.power_matrix_csv:
            power_matrix *= 0
            color   = args.color
            channel = color if color < 4 else color - 4
            group   = 1 if color < 4 else 2
            power_matrix[channel] = load_power_matrix_from_csv(args.power_matrix_csv)
            if group != selected_group:
                print(f"Warning: Color {{color}} uses LEDG{{group}}, switching.")
                selected_group = group
            print(f"Legacy mode: CSV → Color {{color}}, Channel {{channel}}, LEDG{{group}}")

        print(f"Selected LED group: LEDG{{selected_group}}")

        if args.no_calibration:
            print("Calibration disabled")
            calibration_matrix, calibration_applied = None, False
        else:
            calibration_matrix, calibration_applied = load_device_calibration(
                device_id, verbose=True, debug=args.debug
            )

        active_channels = [ch for ch in range(4) if np.any(power_matrix[ch] > 0)]
        if not active_channels:
            print("Error: No channels have non-zero power.")
            sys.exit(1)

        print(f"Active channels: {{active_channels}}")
        print("Preparing protocol...")

        try:
            protocol = prepare_protocol(
                matrix_data=power_matrix,
                on_time=args.on_time,
                period=args.period,
                blue_power_nominal=get_reference_powers(selected_group),
                start_time_matrix=np.zeros((NROWS, NCOLS)),
                on_time_matrix=np.full((NROWS, NCOLS), args.on_time),
                calibration_matrix=calibration_matrix,
                enable_current_scaling=not args.disable_current_scaling,
                lpwm_value=args.lpwm_value,
                verbose=args.verbose,
                led_group=selected_group,
                print_summary=True,
                device_id=device_id,
                temperature=args.temperature,
                verify=not args.no_verify,
                show_progress=not args.no_progress,
                reset_device=not args.no_reset,
            )
        except ValueError as e:
            print(f"Error preparing protocol:\\n  {{e}}")
            sys.exit(1)

        if args.dry_run:
            print("\\nDRY RUN – Protocol not uploaded to device")
            sys.exit(0)

        diya_device = diya(gui=None, device_id=device_id, debug=args.debug)
        diya_device.start()

        try:
            upload_protocol(diya_device, protocol)
        except (ValueError, Exception) as e:
            if args.debug:
                import traceback
                traceback.print_exc()
            sys.exit(1)
        """)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert a DIYA optical plate-map Excel file to a Python script."
    )
    parser.add_argument("input_xlsx",   help="Path to the source .xlsx file")
    parser.add_argument("output_script", nargs="?", default=None,
                        help="Output .py filename (default: <input_stem>_generated.py)")
    parser.add_argument("--sheet",         default="Plate map",
                        help="Sheet name containing the Red/Green blocks (default: 'Plate map')")
    parser.add_argument("--on-time",       type=float, default=5.0)
    parser.add_argument("--period",        type=float, default=5.0)
    parser.add_argument("--temperature",   type=float, default=37.0)
    parser.add_argument("--experiment-id", default=None,
                        help="Experiment label used in script comments (inferred from filename if omitted)")
    args = parser.parse_args()

    input_path = Path(args.input_xlsx)
    if not input_path.exists():
        print(f"Error: file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    experiment_id = args.experiment_id or input_path.stem

    output_path = Path(args.output_script) if args.output_script else \
        input_path.with_name(input_path.stem + "_generated.py")

    print(f"Reading '{args.sheet}' from {input_path} …")
    df = pd.read_excel(input_path, sheet_name=args.sheet, header=None)

    print("Extracting Red matrix …")
    red   = find_block(df, "Red")
    print("Extracting Green matrix …")
    green = find_block(df, "Green")

    print(f"Red   matrix (8×12):\n{red}\n")
    print(f"Green matrix (8×12):\n{green}\n")

    script = generate_script(
        red=red,
        green=green,
        on_time=args.on_time,
        period=args.period,
        temperature=args.temperature,
        experiment_id=experiment_id,
        source_file=input_path.name,
    )

    output_path.write_text(script)
    print(f"Script written to: {output_path}")


if __name__ == "__main__":
    main()