#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto-generated by excel_to_diya.py
# Source: input.xlsx

import numpy as np
import argparse
import sys
from diya import (diya, load_power_matrix_from_csv, prepare_protocol,
                    load_device_config, generate_color_help_text, NROWS, NCOLS,
                    get_reference_powers, load_device_calibration,
                    upload_protocol)

##############################################################################
########################### USER CONFIGURATION ###############################
##############################################################################

# Optical power matrix, in mW/cm2
# 3D array: [channel, row, column]
# Channel 1 = Green light (Color 1, LEDG1)
# Channel 3 = Red   light (Color 3, LEDG1)
DEFAULT_OPTICAL_POWER = np.array([
    # Channel 0 – Blue (unused, all zeros)
    np.zeros((NROWS, NCOLS)),

    # Channel 1 – Green light
    np.array([
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row A
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row B
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row C
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row D
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row E
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row F
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row G
    [0.0,	0.0,	0.0,	0.0,	0.0,	0.0,	0.28,	0.28,	0.28,	0.28,	0.28,	0.28],  # Row H
]),

    # Channel 2 – Yellow-Green / White (unused, all zeros)
    np.zeros((NROWS, NCOLS)),

    # Channel 3 – Red light
    np.array([
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row A
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row B
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row C
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row D
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row E
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row F
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row G
    [2.8,	2.8,	2.8,	2.8,	2.8,	2.8,	0.0,	0.0,	0.0,	0.0,	0.0,	0.0],  # Row H
]),
])

# Timing parameters (in seconds)
DEFAULT_ON_TIME   = 5   # On time
DEFAULT_PERIOD    = 5    # Period (on + off)

# Temperature setpoint (°C)
DEFAULT_TEMPERATURE = 37.0

##############################################################################
############################ ADVANCED OPTIONS ################################
##############################################################################

DEFAULT_START_TIME    = np.zeros((NROWS, NCOLS))
DEFAULT_ON_TIME_MATRIX = None
DEFAULT_GROUP  = 1   # LEDG1 (colors 0-3)
DEFAULT_COLOR  = 0

##############################################################################
######################## END USER CONFIGURATION ##############################
##############################################################################

parser = argparse.ArgumentParser(
    description='Upload input.xlsx protocol to DIYA device'
)
parser.add_argument('device_id', type=str, help='Device ID (e.g., diya00)')

parser.add_argument('--power-matrix-csv',     type=str)
parser.add_argument('--start-time-csv',       type=str)
parser.add_argument('--on-time-csv',          type=str)
parser.add_argument('--color',                type=int, default=DEFAULT_COLOR,
                    help=generate_color_help_text())
parser.add_argument('--led-group',            type=int, default=DEFAULT_GROUP,
                    choices=[1, 2])
parser.add_argument('--on-time',              type=float, default=DEFAULT_ON_TIME)
parser.add_argument('--period',               type=float, default=DEFAULT_PERIOD)
parser.add_argument('--lpwm-value',           type=int)
parser.add_argument('--temperature',          type=float, default=DEFAULT_TEMPERATURE)
parser.add_argument('--no-verify',            action='store_true')
parser.add_argument('--debug',                action='store_true')
parser.add_argument('--no-progress',          action='store_true')
parser.add_argument('--no-reset',             action='store_true')
parser.add_argument('--dry-run',              action='store_true')
parser.add_argument('--no-calibration',       action='store_true')
parser.add_argument('--disable-current-scaling', action='store_true')
parser.add_argument('--verbose',              action='store_true')
args = parser.parse_args()

device_id     = args.device_id
selected_group = args.led_group

power_matrix = DEFAULT_OPTICAL_POWER.copy()

if args.power_matrix_csv:
    power_matrix *= 0
    color   = args.color
    channel = color if color < 4 else color - 4
    group   = 1 if color < 4 else 2
    power_matrix[channel] = load_power_matrix_from_csv(args.power_matrix_csv)
    if group != selected_group:
        print(f"Warning: Color {color} uses LEDG{group}, switching.")
        selected_group = group
    print(f"Legacy mode: CSV → Color {color}, Channel {channel}, LEDG{group}")

print(f"Selected LED group: LEDG{selected_group}")

if args.no_calibration:
    print("Calibration disabled")
    calibration_matrix, calibration_applied = None, False
else:
    calibration_matrix, calibration_applied = load_device_calibration(
        device_id, verbose=True, debug=args.debug
    )

active_channels = [ch for ch in range(4) if np.any(power_matrix[ch] > 0)]
if not active_channels:
    print("Error: No channels have non-zero power.")
    sys.exit(1)

print(f"Active channels: {active_channels}")
print("Preparing protocol...")

try:
    protocol = prepare_protocol(
        matrix_data=power_matrix,
        on_time=args.on_time,
        period=args.period,
        blue_power_nominal=get_reference_powers(selected_group),
        start_time_matrix=np.zeros((NROWS, NCOLS)),
        on_time_matrix=np.full((NROWS, NCOLS), args.on_time),
        calibration_matrix=calibration_matrix,
        enable_current_scaling=not args.disable_current_scaling,
        lpwm_value=args.lpwm_value,
        verbose=args.verbose,
        led_group=selected_group,
        print_summary=True,
        device_id=device_id,
        temperature=args.temperature,
        verify=not args.no_verify,
        show_progress=not args.no_progress,
        reset_device=not args.no_reset,
    )
except ValueError as e:
    print(f"Error preparing protocol:\n  {e}")
    sys.exit(1)

if args.dry_run:
    print("\nDRY RUN – Protocol not uploaded to device")
    sys.exit(0)

diya_device = diya(gui=None, device_id=device_id, debug=args.debug)
diya_device.start()

try:
    upload_protocol(diya_device, protocol)
except (ValueError, Exception) as e:
    if args.debug:
        import traceback
        traceback.print_exc()
    sys.exit(1)
